# Generated by Django 5.2 on 2025-05-08 12:11

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sell_time', '0005_purchase_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='timepackage',
            name='creator_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
